Algoritmo "Solucao18"
// 18) Ler a temperatura em graus celsius e apresenta-la convertida em graus, fahrenheit a formula de conversão é: F = (9*C+160)/5, sendo F a temperatura em fahrenheit e C a temperatura em celsius.

Var
tempCelsius, tempFahrenheit: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite a temperatura celsius: ")
leia(tempCelsius)

tempFahrenheit <- (9*tempCelsius+160)/5

escreva("Temperatura fahrenheit: ", tempFahrenheit)

Fimalgoritmo